import axios from "axios";
import { NextPage } from "next";
import Head from "next/head";
import React, { ChangeEventHandler, useEffect, useState } from "react";
import Input from "../../../components/Input/Input";
import Layout from "../../../components/Layout/Layout";
import { prisma } from "../../../lib/prisma";

type IFileToSend = {
    awsUrltoSendImage: string;
    fileToSend: File;
    fileType: string;
};

const Add: NextPage = () => {
    const [fileToSend, setFileToSend] = useState<IFileToSend>();

    const [readtToUpload, setReadyToUpload] = useState<boolean>(false);

    const [productName, setProductName] = useState<string>("");

    const sendImageToAwsS3 = async (
        awsUrl: string,
        file: File,
        fileType: string | undefined
    ) => {
        await axios
            .put(awsUrl, file, {
                headers: {
                    "Content-Type": String(fileType),
                },
            })
            .then((_) => {
                console.log("Image was added successfully");
            })
            .catch((err) => {
                console.log("Image upload failed", err);
            });
    };

    const getAwsUrlToUpload = async (
        event: { target: { files: File[] } } | any
    ) => {
        let file: File = event.target.files[0];
        let fileParts = file.name.split(".");
        let fileName: string = fileParts[0];
        let fileType: string = fileParts[1];

        await axios
            .post("/api/admin/add-product", {
                fileName: fileName,
                fileType: fileType,
                productId: "28",
            })
            .then((res) => {
                // console.log(res.data);
                setFileToSend({
                    awsUrltoSendImage: res.data.signedRequest as string,
                    fileToSend: file,
                    fileType: fileType,
                });
                setReadyToUpload(true);
            })
            .catch((err) => {
                console.log(err);
            });
    };

    useEffect(() => {
        if (!fileToSend) return;
        // console.log(fileToSend);
        sendImageToAwsS3(
            fileToSend.awsUrltoSendImage,
            fileToSend.fileToSend,
            fileToSend.fileType
        );
    }, [fileToSend]);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" type="image/png" href="/favicon.png" />
            </Head>
            <Layout>
                <div className="px-4 space-y-8">
                    <h2 className="text-2xl">Add product</h2>

                    <div className="space-y-4">
                        <div>
                            <label>
                                Product Name
                                <input
                                    className="w-full h-10 px-3 duration-150 rounded-md shadow-inner bg-black-500 focus:bg-black-800 outline-pink-900 focus:outline-2 focus:outline"
                                    type="text"
                                    name=""
                                    id=""
                                />
                            </label>
                        </div>
                        <div>
                            <label>
                                Product Description
                                <textarea
                                    className="w-full h-40 p-3 duration-150 rounded-md shadow-inner resize-none bg-black-500 focus:bg-black-800 outline-pink-900 focus:outline-2 focus:outline"
                                    name=""
                                    id=""
                                />
                            </label>
                        </div>
                        <div className="flex gap-6">
                            <div className="space-y-6">
                                <div>
                                    <label className="flex flex-col">
                                        Is New
                                        <select
                                            className="h-10 px-1 rounded-md bg-black-500 focus:bg-black-800 outline-pink-900 focus:outline-2 focus:outline"
                                            name=""
                                            id=""
                                        >
                                            <option value="false">False</option>
                                            <option value="true">True</option>
                                        </select>
                                    </label>
                                </div>
                                <div>
                                    <label className="flex flex-col">
                                        Is Bestseller
                                        <select
                                            className="h-10 px-1 rounded-md bg-black-500 focus:bg-black-800 outline-pink-900 focus:outline-2 focus:outline"
                                            name=""
                                            id=""
                                        >
                                            <option value="false">False</option>
                                            <option value="true">True</option>
                                        </select>
                                    </label>
                                </div>
                            </div>
                            <div className="space-y-6">
                                <div>
                                    <label className="flex flex-col">
                                        Price
                                        <input
                                            className="h-10 px-1 rounded-md bg-black-500 focus:bg-black-800 outline-pink-900 focus:outline-2 focus:outline"
                                            type="number"
                                            name=""
                                            id=""
                                        />
                                    </label>
                                </div>
                                <div>
                                    <label className="flex flex-col">
                                        Quantity
                                        <input
                                            className="h-10 px-1 rounded-md bg-black-500 focus:bg-black-800 outline-pink-900 focus:outline-2 focus:outline"
                                            type="number"
                                            name=""
                                            id=""
                                        />
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>

                    <input
                        className="appearance-none"
                        type="file"
                        onChange={getAwsUrlToUpload}
                    />
                    <button type="submit" name="add">
                        add
                    </button>
                </div>
                <div>{/* <button>Send</button> */}</div>
            </Layout>
        </>
    );
};

export default Add;
