import type { NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";
import { useRouter } from "next/router";
import Menu from "../../components/Menu/Menu";
import SideMenu from "../../components/Menu/SideMenu";
import Image from "next/image";
import { StarIcon } from "@heroicons/react/solid";
import { PlusCircleIcon } from "@heroicons/react/outline";
import Link from "next/link";
import Layout from "../../components/Layout/Layout";

const Products: NextPage = () => {
    const { data: session, status } = useSession();
    console.log("status:", status, session);

    const router = useRouter();

    if (status === "unauthenticated") {
        router.push("/");
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favico.ico" />
            </Head>
            <Layout>Product</Layout>
        </>
    );
};

export default Products;
