import type { NextPage } from "next";
import Head from "next/head";
import LoginForm from "../components/LoginForm/LoginForm";
import SignUpForm from "../components/LoginForm/SignUpForm";

const SignUp: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favico.ico" />
            </Head>
            <main>
                <div className="flex items-center justify-center w-screen h-screen">
                    <SignUpForm />
                </div>
            </main>
        </>
    );
};

export default SignUp;
