import type { NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";
import Layout from "../../../components/Layout/Layout";

const Customers: NextPage = () => {
    return (
        <>
            <Head>
                <title>NextShop | Admin panel</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.png" />
            </Head>
            <Layout>Customers</Layout>
        </>
    );
};

export default Customers;
